services:
  cms_svc:
    container_name: cms-svc
    build: ./
    ports:
      - "9000:9000"
    networks:
      - cms-net
    depends_on:
      - postgres_svc
  postgres_svc:
    container_name: postgres-svc
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - cms-net
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}

networks:
  cms-net:
    driver: bridge